[package]
name = "ddos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "gzip", "stream", "blocking", "rustls-tls"] }
trust-dns-resolver = "0.20"
futures = "0.3"
